### ISSUE TITLE
Segmentation fault when closing while loading wallets

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin-core/gui#689]
Steps to reproduce:

* Exit or CTRL+C while the "Loading wallets" *pop-up* is visible.

```
Thread 1 "bitcoin-qt" received signal SIGSEGV, Segmentation fault.


Thread 1 (Thread 0x7ffff5935080 (LWP 52927) "bitcoin-qt"):
#0  0x00007ffff78cf1ae in QObjectPrivate::addConnection(int, QObjectPrivate::Connection*) () at /lib64/libQt5Core.so.5
#1  0x00007ffff78d5067 in QObjectPrivate::connectImpl(QObject const*, int, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*) () at /lib64/libQt5Core.so.5
#2  0x00007ffff78d54d5 in QObject::connectImpl(QObject const*, void**, QObject const*, void**, QtPrivate::QSlotObjectBase*, Qt::ConnectionType, int const*, QMetaObject const*) () at /lib64/libQt5Core.so.5
#3  0x00005555556c700d in QObject::connect<void (WalletModel::*)(interfaces::WalletBalances const&), void (SendCoinsDialog::*)(interfaces::WalletBalances const&)>(QtPrivate::FunctionPointer<void (WalletModel::*)(interfaces::WalletBalances const&)>::Object const*, void (WalletModel::*)(interfaces::WalletBalances const&), QtPrivate::FunctionPointer<void (SendCoinsDialog::*)(interfaces::WalletBalances const&)>::Object const*, void (SendCoinsDialog::*)(interfaces::WalletBalances const&), Qt::ConnectionType) (sender=0x7fff28001900, signal=(void (WalletModel::*)(WalletModel * const, const interfaces::WalletBalances &)) 0x5555556c83e0 <SendCoinsDialog::setBalance(interfaces::WalletBalances const&)>, receiver=0x555556f20860, slot=(void (SendCoinsDialog::*)(SendCoinsDialog * const, const interfaces::WalletBalances &)) 0x555556e4c2c0, this adjustment 93825023925952, type=Qt::AutoConnection) at /usr/include/qt5/QtCore/qobject.h:264
#4  SendCoinsDialog::setModel(WalletModel*) (this=0x555556f20860, _model=0x7fff28001900) at qt/sendcoinsdialog.cpp:167
#5  0x000055555568726a in WalletView::WalletView(WalletModel*, PlatformStyle const*, QWidget*) (this=0x555556650360, wallet_model=<optimized out>, _platformStyle=<optimized out>, parent=<optimized out>) at qt/walletview.cpp:65
#6  0x000055555560321a in BitcoinGUI::addWallet(WalletModel*) (this=0x555556fde0e0, walletModel=0x7fff28001900) at qt/bitcoingui.cpp:697
#7  0x0000555555609c22 in _ZZN7GUIUtil20ExceptionSafeConnectIP16WalletControllerMS1_FvP11WalletModelEP10BitcoinGUIMS7_FvS4_EEEDaT_T0_T1_T2_N2Qt14ConnectionTypeEENKUlDpOT_E_clIJRS4_EEEDaSJ_ (this=0x5555566cebd0, args=<optimized out>) at ./qt/guiutil.h:400
#8  0x0000555555609bc0 in _ZN9QtPrivate11FunctorCallINS_11IndexesListIJLi0EEEENS_4ListIJP11WalletModelEEEvZN7GUIUtil20ExceptionSafeConnectIP16WalletControllerMS9_FvS5_EP10BitcoinGUIMSD_FvS5_EEEDaT_T0_T1_T2_N2Qt14ConnectionTypeEEUlDpOT_E_E4callERSQ_PPv (f=..., arg=0x5) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:146
#9  _ZN9QtPrivate7FunctorIZN7GUIUtil20ExceptionSafeConnectIP16WalletControllerMS3_FvP11WalletModelEP10BitcoinGUIMS9_FvS6_EEEDaT_T0_T1_T2_N2Qt14ConnectionTypeEEUlDpOT_E_Li1EE4callINS_4ListIJS6_EEEvEEvRSM_PvPSS_ (f=..., arg=0x5) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:256
#10 _ZN9QtPrivate18QFunctorSlotObjectIZN7GUIUtil20ExceptionSafeConnectIP16WalletControllerMS3_FvP11WalletModelEP10BitcoinGUIMS9_FvS6_EEEDaT_T0_T1_T2_N2Qt14ConnectionTypeEEUlDpOT_E_Li1ENS_4ListIJS6_EEEvE4implEiPNS_15QSlotObjectBaseEP7QObjectPPvPb (which=<optimized out>, this_=<optimized out>, r=0x555557728670, a=0x5, ret=0x7fffffffcd18) at /usr/include/qt5/QtCore/qobjectdefs_impl.h:443
#11 0x00007ffff78d2ec4 in QObject::event(QEvent*) () at /lib64/libQt5Core.so.5
#12 0x00007ffff6faed12 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#13 0x00007ffff78a8278 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#14 0x00007ffff78ab5e4 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () at /lib64/libQt5Core.so.5
#15 0x00007ffff78f9897 in postEventSourceDispatch(_GSource*, int (*)(void*), void*) () at /lib64/libQt5Core.so.5
#16 0x00007ffff5266cbf in g_main_context_dispatch () at /lib64/libglib-2.0.so.0
#17 0x00007ffff52bc598 in g_main_context_iterate.constprop () at /lib64/libglib-2.0.so.0
#18 0x00007ffff5263f40 in g_main_context_iteration () at /lib64/libglib-2.0.so.0
#19 0x00007ffff78f938a in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#20 0x00007ffff78a6cca in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib64/libQt5Core.so.5
#21 0x00007ffff78aed92 in QCoreApplication::exec() () at /lib64/libQt5Core.so.5
#22 0x00005555555f25fd in GuiMain(int, char**) (argc=<optimized out>, argv=<optimized out>) at qt/bitcoin.cpp:697
#23 0x00005555555ecc4a in main(int, char**) (argc=-67945086, argv=0x3) at qt/main.cpp:24

**Comment by MarcoFalke** [comment]
Also happens on 23.x

**Comment by hebasto** [comment]
@MarcoFalke 

Can you confirm that https://github.com/bitcoin-core/gui/pull/693 fixes this issue for you?
